gpu/config: Fix build with gcc-13
* fixes:
FAILED: obj/gpu/config/config_sources/gpu_feature_info.o
x86_64-webos-linux-g++  -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 --sysroot=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot -MMD -MF obj/gpu/config/config_sources/gpu_feature_info.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=13 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGPU_IMPLEMENTATION -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DUSE_EGL -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DANGLE_DELEGATE_WORKERS -DANGLE_ENABLE_NULL -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DVK_NO_PROTOTYPES -I../../git/src/third_party/mesa_headers -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/libwebp/src -I../../git/src/third_party/vulkan-deps/vulkan-headers/src/include -Igen/third_party/dawn/src/include -I../../git/src/third_party/dawn/src/include -I../../git/src/third_party/crashpad/crashpad -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -I../../git/src/third_party/crashpad/crashpad/compat/linux -I../../git/src/third_party/crashpad/crashpad/compat/non_win -I../../git/src/third_party/zlib -I../../git/src/third_party/skia -I../../git/src/third_party/wuffs/src/release/c -I../../git/src/third_party/vulkan/include -I../../git/src/third_party/icu/source/common -I../../git/src/third_party/icu/source/i18n -I../../git/src/third_party/ced/src -I../../git/src/third_party/re2/src -I../../git/src/third_party/khronos -I../../git/src/gpu -I../../git/src/third_party/angle/include -I../../git/src/third_party/angle/src -I../../git/src/third_party/angle/src/common/third_party/base -Igen/angle -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/lib/glib-2.0/include -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../git/src/gpu/config/gpu_feature_info.cc -o obj/gpu/config/config_sources/gpu_feature_info.o
In file included from ../../git/src/gpu/config/gpu_feature_info.cc:5:
../../git/src/gpu/config/gpu_feature_info.h:62:15: error: 'uint32_t' was not declared in this scope
   62 |   std::vector<uint32_t> applied_gpu_blocklist_entries;
      |               ^~~~~~~~
../../git/src/gpu/config/gpu_feature_info.h:13:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   12 | #include "gpu/gpu_export.h"
  +++ |+#include <cstdint>
   13 |

Upstream-Status: Pending

Change-Id: I6482a3a6ea2584f696a45f0bc4dc2d4f019d4287
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/344624
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>