[op][n_upsable][clang][webos] Build webruntime with clang for WebOS
:Release Notes:
Build webruntime with clang for WebOS.

:Detailed Notes:
Originally reviewed on http://gpro.lge.com/c/webosose/chromium91/+/330333

Rework clang_webos_arm to be a primary toolchain to build libcbe as
opposed to its initial purpose, to build libjpeg turbo for Strafish.

Added missing -pthread for linker as it is not passed from compiler.

Fixed clang compilation error: can't capture static variables in
lambda expression.

:Testing Performed:
Execute: LD_LIBRARY_PATH=/usr/lib/cbe /usr/bin/app-shell/run_app_shell --folder /usr/palm/applications/com.webos.app.enactbrowser --appid com.webos.app.enactbrowser

:QA Notes:

:Issues Addressed:
[WRO-2081] Build app_shell and all required components with clang and run on TB

Depends-on: http://gpro.lge.com/328304
Change-Id: Ie5729a6948c0bccaaa04d45585e7dcb9d4c38711
Reviewed-on: http://gpro.lge.com/c/webosose/chromium91/+/330333
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-by: Igor Britsky <igor.britsky@lge.com>
Reviewed-by: Vladislav Mukulov <vladislav.mukulov@lge.com>
Reviewed-by: Alexander Kovalenko <alexander.kovalenko@lge.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Igor Britsky <igor.britsky@lge.com>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/335092
Tested-by: <ivan.pivovarov@lge.com>