Revert "[oe][n_upsable][wayland] Implement GPU vsync provider for wayland"
:Release Notes:
This reverts commit aebff73322fd04061cc4bd013b7b72aa22eaeef9.
(http://gpro.lge.com/c/webos-pro/chromium/+/332299)

:Detailed Notes:
Temporary revert the patch since it causes below link error.
It seems the link error occurs when the GOW build is enabled.

|
/home/drabble/webOS/Number1/Upgradeto94/work/build-webos/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-pro.20-r54.1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/../../libexec/aarch64-webos-linux/gcc/aarch64-webos-linux/9.3.0/ld.gold:
error: obj/ozone/wayland/wayland/presentation-time-protocol.o: multiple
definition of 'wp_presentation_feedback_interface'
|
/home/drabble/webOS/Number1/Upgradeto94/work/build-webos/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-pro.20-r54.1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/../../libexec/aarch64-webos-linux/gcc/aarch64-webos-linux/9.3.0/ld.gold:
obj/third_party/wayland-protocols/presentation_time_protocol/presentation-time-protocol.o:
previous definition here
|
/home/drabble/webOS/Number1/Upgradeto94/work/build-webos/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-pro.20-r54.1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/../../libexec/aarch64-webos-linux/gcc/aarch64-webos-linux/9.3.0/ld.gold:
error: obj/ozone/wayland/wayland/presentation-time-protocol.o: multiple
definition of 'wp_presentation_interface'
|
/home/drabble/webOS/Number1/Upgradeto94/work/build-webos/BUILD/work/raspberrypi4_64-webos-linux/webruntime/94.0.4606.128-pro.20-r54.1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/../../libexec/aarch64-webos-linux/gcc/aarch64-webos-linux/9.3.0/ld.gold:
obj/third_party/wayland-protocols/presentation_time_protocol/presentation-time-protocol.o:
previous definition here
| collect2: error: ld returned 1 exit status

:Testing Performed:
Build succeeds

:QA Notes:
Test-cases: N/A

:Issues Addressed:
[WRO-7517] Setup OSE branch using Continuous upgrade PoC result

Change-Id: Iffab82e758e6e16420774fbe29ef152efa93ce4a
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/332675
Tested-by: Youngsoo Choi <youngsoo.choi@lge.com>
Reviewed-by: Youngsoo Choi <youngsoo.choi@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>