[op][upsable][build] wayland/extensions/webos/host: fix build with newer toolchain
:Release Notes:
fix build with newer toolchain

:Detailed Notes:
Fixes:
| FAILED: obj/ui/ozone/platform/wayland/extensions/webos/webos/webos_accelerometer_wrapper.o
| x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/OE/lge/build/webos-pro/kirkstone/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-pro.11-r52.1/recipe-sysroot -MMD -MF obj/ui/ozone/platform/wayland/extensions/webos/webos/webos_accelerometer_wrapper.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=11 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/libwebp/src -I../../git/src/third_party/skia -I../../git/src/third_party/wuffs/src/release/c -I../../git/src/third_party/vulkan/include -I../../git/src/third_party/vulkan-deps/vulkan-headers/src/include -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -I../../git/src/third_party/ced/src -I../../git/src/third_party/icu/source/common -I../../git/src/third_party/icu/source/i18n -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -I/OE/lge/build/webos-pro/kirkstone/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-pro.11-r52.1/recipe-sysroot/usr/include/glib-2.0 -I/OE/lge/build/webos-pro/kirkstone/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-pro.11-r52.1/recipe-sysroot/usr/lib/glib-2.0/include -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_accelerometer_wrapper.cc -o obj/ui/ozone/platform/wayland/extensions/webos/webos/webos_accelerometer_wrapper.o
| ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_accelerometer_wrapper.cc:27:16: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
|    27 | constexpr std::uint32_t kEnable = 1;
|       |                ^~~~~~~~
|       |                wint_t
| ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_accelerometer_wrapper.cc:28:16: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
|    28 | constexpr std::uint32_t kDisable = 0;
|       |                ^~~~~~~~
|       |                wint_t
| ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_accelerometer_wrapper.cc: In member function 'virtual void ui::WebosAccelerometerWrapper::RequestData(bool)':
| ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_accelerometer_wrapper.cc:47:52: error: 'kEnable' was not declared in this scope
|    47 |                                       is_enabled ? kEnable : kDisable);
|       |                                                    ^~~~~~~
| ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_accelerometer_wrapper.cc:47:62: error: 'kDisable' was not declared in this scope
|    47 |                                       is_enabled ? kEnable : kDisable);
|       |                                                              ^~~~~~~~

and

FAILED: obj/ui/ozone/platform/wayland/extensions/webos/webos/webos_gyroscope_wrapper.o
x86_64-webos-linux-g++  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/OE/lge/build/webos-pro/kirkstone/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-pro.11-r52.1/recipe-sysroot -MMD -MF obj/ui/ozone/platform/wayland/extensions/webos/webos/webos_gyroscope_wrapper.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_NETWORK_ERROR_PAGE_CONTROLLER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DENABLE_NETCAST_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DUSE_SINGLE_WINDOW_MODE=1 -DWEBOS_SUBMISSION_NUMBER=11 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/libwebp/src -I../../git/src/third_party/skia -I../../git/src/third_party/wuffs/src/release/c -I../../git/src/third_party/vulkan/include -I../../git/src/third_party/vulkan-deps/vulkan-headers/src/include -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -I../../git/src/third_party/ced/src -I../../git/src/third_party/icu/source/common -I../../git/src/third_party/icu/source/i18n -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -I/OE/lge/build/webos-pro/kirkstone/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-pro.11-r52.1/recipe-sysroot/usr/include/glib-2.0 -I/OE/lge/build/webos-pro/kirkstone/BUILD/work/qemux86_64-webos-linux/webruntime/94.0.4606.128-pro.11-r52.1/recipe-sysroot/usr/lib/glib-2.0/include -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_gyroscope_wrapper.cc -o obj/ui/ozone/platform/wayland/extensions/webos/webos/webos_gyroscope_wrapper.o
../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_gyroscope_wrapper.cc:27:16: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
   27 | constexpr std::uint32_t kEnable = 1;
      |                ^~~~~~~~
      |                wint_t
../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_gyroscope_wrapper.cc:28:16: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
   28 | constexpr std::uint32_t kDisable = 0;
      |                ^~~~~~~~
      |                wint_t
../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_gyroscope_wrapper.cc: In member function 'virtual void ui::WebosGyroscopeWrapper::RequestData(bool)':
../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_gyroscope_wrapper.cc:46:48: error: 'kEnable' was not declared in this scope
   46 |                                   is_enabled ? kEnable : kDisable);
      |                                                ^~~~~~~
../../git/src/ui/ozone/platform/wayland/extensions/webos/host/webos_gyroscope_wrapper.cc:46:58: error: 'kDisable' was not declared in this scope
   46 |                                   is_enabled ? kEnable : kDisable);
      |                                                          ^~~~~~~~

:Testing Performed:
Build succeeds

:QA Notes:
N/A

:Issues Addressed:
[WRO-7517] Setup OSE branch using Continuous upgrade PoC result

Change-Id: I10858123a4c2bf9d2fbfb9e92417a199f0242b5c
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/336309
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Youngsoo Choi <youngsoo.choi@lge.com>
Tested-by: Youngsoo Choi <youngsoo.choi@lge.com>