components/crash: Fix build with gcc-13
Fixes:
FAILED: obj/components/crash/core/app/lib/crash_reporter_client.o
x86_64-webos-linux-g++  -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 --sysroot=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot -MMD -MF obj/components/crash/core/app/lib/crash_reporter_client.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=13 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/lib/glib-2.0/include -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -c ../../git/src/components/crash/core/app/crash_reporter_client.cc -o obj/components/crash/core/app/lib/crash_reporter_client.o
In file included from ../../git/src/components/crash/core/app/crash_reporter_client.cc:5:
../../git/src/components/crash/core/app/crash_reporter_client.h:109:32: error: 'uint64_t' has not been declared
  109 |                                uint64_t crash_pid);
      |                                ^~~~~~~~
../../git/src/components/crash/core/app/crash_reporter_client.cc:104:43: error: 'uint64_t' has not been declared
  104 |                                           uint64_t crash_pid) {
      |                                           ^~~~~~~~

Upstream-Status: Pending

Change-Id: I2c893b5d12cd8d48626469d10667f6c04aacda24
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/344627
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>