third_party/blink: Fix build with gcc-13
Fixes:
FAILED: obj/third_party/blink/renderer/modules/exported/exported/web_ax_context.o
x86_64-webos-linux-g++  -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 --sysroot=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot -MMD -MF obj/third_party/blink/renderer/modules/exported/exported/web_ax_context.o.d -DBLINK_MODULES_IMPLEMENTATION=1 -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=13 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DWEBP_EXTERN=extern -DUSE_EGL -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_ENABLE_TRACING=1 -DU_ENABLE_RESOURCE_TRACING=0 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DWEBRTC_USE_BUILTIN_ISAC_FIX=0 -DWEBRTC_USE_BUILTIN_ISAC_FLOAT=1 -DWEBRTC_HAVE_SCTP -DNO_MAIN_THREAD_WRAPPING -DSK_UNTIL_CRBUG_1187654_IS_FIXED -DSK_CODEC_DECODES_PNG -DSK_CODEC_DECODES_WEBP -DSK_ENCODE_PNG -DSK_ENCODE_WEBP -DSK_ENABLE_SKSL -DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\" -DSK_GL -DSK_CODEC_DECODES_JPEG -DSK_ENCODE_JPEG -DSK_HAS_WUFFS_LIBRARY -DSK_VULKAN_HEADER=\"../../skia/config/SkVulkanConfig.h\" -DSK_VULKAN=1 -DSK_SUPPORT_GPU=1 -DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\" -DV8_COMPRESS_POINTERS -DV8_COMPRESS_POINTERS_IN_SHARED_CAGE -DV8_31BIT_SMIS_ON_64BIT_ARCH -DV8_DEPRECATION_WARNINGS -DCPPGC_CAGED_HEAP -DCRASHPAD_ZLIB_SOURCE_EXTERNAL -DLEVELDB_PLATFORM_CHROMIUM=1 -DWTF_USE_WEBAUDIO_PFFFT=1 -DUSE_LIBJPEG_TURBO=1 -DLIBXSLT_STATIC -I../../git/src/neva -Igen/neva -I../../git/src -Igen -I../../git/src/third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -I../../git/src/third_party/libyuv/include -I../../git/src/third_party/jsoncpp/source/include -I../../git/src/third_party/libwebp/src -I../../git/src/third_party/vulkan-deps/vulkan-headers/src/include -Igen/third_party/dawn/src/include -I../../git/src/third_party/dawn/src/include -I../../git/src/third_party/khronos -I../../git/src/gpu -I../../git/src/third_party/abseil-cpp -I../../git/src/third_party/boringssl/src/include -I../../git/src/third_party/protobuf/src -Igen/protoc_out -I../../git/src/third_party/ced/src -I../../git/src/third_party/icu/source/common -I../../git/src/third_party/icu/source/i18n -Igen/net/third_party/quiche/src -I../../git/src/net/third_party/quiche/overrides -I../../git/src/net/third_party/quiche/src/common/platform/default -I../../git/src/net/third_party/quiche/src -I../../git/src/third_party/webrtc_overrides -I../../git/src/third_party/webrtc -Igen/third_party/webrtc -I../../git/src/third_party/skia -I../../git/src/third_party/wuffs/src/release/c -I../../git/src/third_party/vulkan/include -I../../git/src/v8/include -Igen/v8/include -I../../git/src/third_party/mesa_headers -I../../git/src/third_party/crashpad/crashpad -I../../git/src/third_party/crashpad/crashpad/compat/linux -I../../git/src/third_party/crashpad/crashpad/compat/non_win -I../../git/src/third_party/zlib -I../../git/src/third_party/libwebm/source -I../../git/src/third_party/leveldatabase -I../../git/src/third_party/leveldatabase/src -I../../git/src/third_party/leveldatabase/src/include -I../../git/src/third_party/libjpeg_turbo -I../../git/src/third_party/iccjpeg -I../../git/src/third_party/libpng -I../../git/src/third_party/ots/src/include -I../../git/src/third_party/libxml/src/include -I../../git/src/third_party/libxml/linux/include -I../../git/src/third_party/libxslt/src -I../../git/src/third_party/snappy/src -I../../git/src/third_party/snappy/linux -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -fvisibility=hidden -g1 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/include/glib-2.0 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/lib/glib-2.0/include -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/include/nss3 -I/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot/usr/include/nspr -DLIBXML_STATIC= -std=gnu++14 -Wno-narrowing -Wno-class-memaccess -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-deprecated-declarations -c ../../git/src/third_party/blink/renderer/modules/exported/web_ax_context.cc -o obj/third_party/blink/renderer/modules/exported/exported/web_ax_context.o
In file included from ../../git/src/third_party/blink/renderer/platform/graphics/paint/property_tree_state.h:10,
                 from ../../git/src/third_party/blink/renderer/platform/graphics/paint/ref_counted_property_tree_state.h:9,
                 from ../../git/src/third_party/blink/renderer/platform/graphics/paint/paint_chunk.h:18,
                 from ../../git/src/third_party/blink/renderer/platform/graphics/paint/paint_artifact.h:9,
                 from ../../git/src/third_party/blink/renderer/platform/graphics/paint/paint_controller.h:20,
                 from ../../git/src/third_party/blink/renderer/core/frame/local_frame_view.h:53,
                 from ../../git/src/third_party/blink/renderer/modules/accessibility/ax_object_cache_impl.h:45,
                 from ../../git/src/third_party/blink/renderer/modules/exported/web_ax_context.cc:11:
../../git/src/third_party/blink/renderer/platform/graphics/paint/effect_paint_property_node.h:319:3: error: declaration of 'const cc::DocumentTransitionSharedElementId& blink::EffectPaintPropertyNode::DocumentTransitionSharedElementId() const' changes meaning of 'DocumentTransitionSharedElementId' [-fpermissive]
  319 |   DocumentTransitionSharedElementId() const {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../git/src/third_party/blink/renderer/platform/graphics/paint/effect_paint_property_node.h:131:5: note: used here to mean 'class cc::DocumentTransitionSharedElementId'
  131 |     DocumentTransitionSharedElementId document_transition_shared_element_id;
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../git/src/third_party/blink/renderer/platform/graphics/document_transition_shared_element_id.h:8,
                 from ../../git/src/third_party/blink/renderer/core/document_transition/document_transition.h:14,
                 from ../../git/src/third_party/blink/renderer/core/frame/local_frame_view.h:38:
../../git/src/cc/document_transition/document_transition_shared_element_id.h:17:17: note: declared here
   17 | class CC_EXPORT DocumentTransitionSharedElementId {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: Iea8f8c7db78f6eb273a314b878fac5ee1fa99ab0
Upstream-Status: Pending
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/344637
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>