[op][n_upsable][zlib] Removing the unsetting _FILE_OFFSET_BITS
:Release Notes:
Removed the unsetting _FILE_OFFSET_BITS

:Detailed Notes:
This is cherry-pick from:
https://github.com/madler/zlib/pull/764
    This does not work when enabling 64bit time_t with glibc which is
    enabled with -D_TIME_BITS=64, since it also needs
    _FILE_OFFSET_BITS=64 and this does not work when its undefined
    explicitly

Apply https://github.com/madler/zlib/pull/764 on bundled zlib to fix
build with time64.inc as in:
https://git.openembedded.org/openembedded-core/tree/meta/conf/distro/include/time64.inc?id=18df5694796bcfee73c3765bc991bcef055466e3

FAILED: obj/third_party/zlib/zlib/gzclose.o
cc1: warning: switch '-mcpu=cortex-a8' conflicts with switch '-march=armv7-a+simd'
In file included from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-webos-linux-gnueabi/webruntime/94-r59.2/recipe-sysroot/usr/include/features.h:392,
                 from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-webos-linux-gnueabi/webruntime/94-r59.2/recipe-sysroot/usr/include/bits/libc-header-start.h:33,
                 from /OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-webos-linux-gnueabi/webruntime/94-r59.2/recipe-sysroot/usr/include/stdio.h:27,
                 from ../../git/src/third_party/zlib/gzguts.h:21,
                 from ../../git/src/third_party/zlib/gzclose.c:6:
/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/cortexa8t2hf-neon-webos-linux-gnueabi/webruntime/94-r59.2/recipe-sysroot/usr/include/features-time64.h:26:5: error: #error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
   26 | #   error "_TIME_BITS=64 is allowed only with _FILE_OFFSET_BITS=64"
      |     ^~~~~

:Testing Performed:
Build

:QA Notes:
N/A

:Issues Addressed:
[WRP-7446] Support integration of changes to meta

Change-Id: I2d7ce8ca6701d1eed610f459d6709d20ea577d0b
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/344126
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Commit Msg Checker <commit_msg@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Reviewed-by: Vladislav Mukulov <vladislav.mukulov@lge.com>
Reviewed-by: Jose Dapena Paz <j.dapena@lgepartner.com>
Reviewed-by: Donghyun Kim <donghyun11.kim@lge.com>
Tested-by: Test BTS <test.bts@lge.com>