dawn-tint: Fix build with gcc-13
* fixes:
FAILED: obj/third_party/dawn/third_party/tint/src/libtint_spv_writer_src/operand.o
x86_64-webos-linux-g++  -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 --sysroot=/OE/build/luneos-mickledore/webos-ports/tmp-glibc/work/corei7-64-webos-linux/webruntime/94-r59.2/recipe-sysroot -MMD -MF obj/third_party/dawn/third_party/tint/src/libtint_spv_writer_src/operand.o.d -DENABLE_BROWSER_CONTROL_WEBAPI=1 -DENABLE_SAMPLE_WEBAPI=1 -DENABLE_MEMORYMANAGER_WEBAPI=1 -DENABLE_WEBOS_SERVICE_BRIDGE_WEBAPI=1 -DENABLE_WEBOS_SYSTEM_WEBAPI=1 -DNEVA_DCHECK_ALWAYS_ON=1 -DOZONE_PLATFORM_WAYLAND_EXTERNAL=1 -DNEVA_OZONE_PLATFORM_WAYLAND=1 -DOS_WEBOS=1 -DNEVA_VIDEO_HOLE=1 -DUSE_NEVA_APPRUNTIME=1 -DUSE_NEVA_BROWSER_SERVICE=1 -DUSE_WEBRISK_SERVICE=1 -DENABLE_WEBM_VIDEO_CODECS=1 -DUSE_CBE=1 -DUSE_PMLOG=1 -DUSE_NEVA_SUSPEND_MEDIA_CAPTURE=1 -DUSE_FILESCHEME_CODECACHE=1 -DWEBOS_SUBMISSION_NUMBER=13 -DUSE_LOCAL_STORAGE_TRACKER=1 -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DTINT_BUILD_SPV_READER=1 -DTINT_BUILD_SPV_WRITER=1 -DTINT_BUILD_WGSL_READER=1 -DTINT_BUILD_WGSL_WRITER=1 -DTINT_BUILD_MSL_WRITER=1 -DTINT_BUILD_HLSL_WRITER=1 -I../../git/src/neva -Igen/neva -I../../git/src -Igen -Igen/third_party/dawn/third_party/tint/src -I../../git/src/third_party/dawn/third_party/tint -I../../git/src/third_party/vulkan-deps/spirv-headers/src/include -I../../git/src/third_party/vulkan-deps/spirv-tools/src -I../../git/src/third_party/vulkan-deps/spirv-tools/src/include -I../../git/src/third_party/dawn/third_party/tint/include -Wno-unused-variable -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -msse3 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -fvisibility=hidden -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-attributes -Wno-missing-field-initializers -Wno-unused-parameter -std=gnu++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-narrowing -Wno-class-memaccess -c ../../git/src/third_party/dawn/third_party/tint/src/writer/spirv/operand.cc -o obj/third_party/dawn/third_party/tint/src/libtint_spv_writer_src/operand.o
In file included from ../../git/src/third_party/dawn/third_party/tint/src/writer/spirv/operand.cc:15:
../../git/src/third_party/dawn/third_party/tint/src/writer/spirv/operand.h:40:22: error: 'uint32_t' has not been declared
   40 |   static Operand Int(uint32_t val);
      |                      ^~~~~~~~
../../git/src/third_party/dawn/third_party/tint/src/writer/spirv/operand.h:63:16: error: 'uint32_t' has not been declared
   63 |   void set_int(uint32_t val) { int_val_ = val; }
      |                ^~~~~~~~
../../git/src/third_party/dawn/third_party/tint/src/writer/spirv/operand.h:76:3: error: 'uint32_t' does not name a type
   76 |   uint32_t length() const;
      |   ^~~~~~~~
../../git/src/third_party/dawn/third_party/tint/src/writer/spirv/operand.h:20:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   19 | #include <vector>
  +++ |+#include <cstdint>
   20 |

Upstream-Status: Pending

Change-Id: I816d1a7ee1b05852da561195e6e5a6537e993e38
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Reviewed-on: http://gpro.lge.com/c/webosose/chromium94/+/344616
Reviewed-by: Ban Word Checker <ban_word@lge.com>
Reviewed-by: Martin Jansa <martin2.jansa@lgepartner.com>
Tested-by: Martin Jansa <martin2.jansa@lgepartner.com>